
title: Free, Libre and Open Works
email: sanglorian@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This wiki celebrates culture and knowledge that you can copy and share without breaking the law, with a particular focus on free, libre and open works that can be shared and adapted by any person for any purpose, commercial or otherwise.
baseurl: "/flow" 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

feed:
  collections:
    entries:
      path: "/entries.xml"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  languages:
    output: true
    permalink: /language/:name/
  groupings:
    output: true
  entries:
    output: true
  licenses:
    output: true
    permalink: /license/:name/
  funding-tools:
    output: true
    permalink: /funding/:name/ 
  staging_entries:
    output: false
  genres:
    output: true
    permalink: /genre/:name/